version: 2.1

defaults: &defaults
    #working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"

jobs:
  build :
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *defaults
    steps:
    - checkout
    - run: run npm i
    - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test